### PR TITLE
Create road map

### PR DESCRIPTION
**Pull request by LinhNguyenLe2109**
Road map is created

New path : /route

Opinion: Since this is a new design, we still have a lot of space which we can add description into each milestone

### CODE REVIEW

**Comment by Santosharawn7** [comment]
@LinhNguyenLe2109 

Please add a horizontal view for big screens. I would prefer Title on the opposite side, it would look better

image

Make something like this but smaller for Mobile Screens and yeah similarly would prefer Title on the opposite side, it would look better

image

Let me know if possible by tomorrow, else we will work with another solution with designers

**Comment by LinhNguyenLe2109** [comment]
@Santosharawn7 can you check again, there should be another view now

image

**Comment by Santosharawn7** [comment]
@LinhNguyenLe2109 Lets wait for logo from Giselle and we can do this together

**Comment by LinhNguyenLe2109** [comment]
image
image

**Comment by Santosharawn7** [comment]
Much better, lets replace that Icon once we have it

**Comment by Santosharawn7** [comment]
@LinhNguyenLe2109 

Giselle has updated the icon, change that and please resolve the merge conflict.

**Pull request merged**
